networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
    driver: local


services:
  mydb:
    image: postgres
    container_name: bdd
    ports:
      - "${BDD_PORT}:${BDD_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
  
  python-server:
    image: ghcr.io/dockerappsandbox/pythonserver:prod
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mydb

  front:
    image: ghcr.io/dockerappsandbox/front:prod
    ports:
    - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - mydb
      - python-server
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_SERVER_PYTHON_URL: ${NEXT_PUBLIC_SERVER_PYTHON_URL}

  back:
    image: ghcr.io/dockerappsandbox/back:prod
    ports: 
      - "${BACK_PORT}:${BACK_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      BACK_PORT: ${BACK_PORT}
    depends_on:
      - mydb
      - python-server
      - front
    restart: unless-stopped
    networks:
      - mynetwork
