services:
  mydb:
    image: postgres
    container_name: bdd
    ports:
      - "${BDD_PORT}:${BDD_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      mynetwork: 
        ipv4_address: 172.28.0.5
  
  python-http-server:
    build:
      context: .
      dockerfile: ./Server-Python/Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mydb
    volumes:
      - ./Server-Python/images:/app/images
    networks:
      mynetwork: 
        ipv4_address: 172.28.0.4

  front:
    build:
      context: .
      dockerfile: ./Front/Dockerfile-dev
    volumes:
     - ./Front/src:/app/src
      - ./Front/node_modules:/app/node_modules
    ports:
    - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - mydb
      - python-http-server
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_SERVER_PYTHON_URL: ${NEXT_PUBLIC_SERVER_PYTHON_URL}
    networks:
      mynetwork:
        ipv4_address: 172.28.0.3

  back:
    build: 
      context: .
      dockerfile: ./Back/dockerfile-dev
    volumes:
      - ./Back/src:/app/src
      - ./Back/node_modules:/app/node_modules
    ports: 
      - "${BACK_PORT}:${BACK_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mydb
      - python-http-server
      - front
    networks:
      mynetwork:
        ipv4_address: 172.28.0.2

networks:
  mynetwork:
    external: true

volumes:
  postgres_data:
    driver: local