services:
   python-http-server:
    build:
      context: .
      dockerfile: dockerfile-python
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mydb
    volumes:
      - ./images:/app/images
    networks:
      mynetwork: 
        ipv4_address: 172.28.0.4

networks:
  mynetwork:
    external: true