# FROM node:20.10.0-alpine AS builder

# WORKDIR /app

# COPY package.json package-lock.json ./

# RUN npm install 

# COPY prisma ./prisma

# COPY . .

# RUN npx prisma generate

# RUN npm run build

# FROM node:20.10.0-alpine AS runner


# WORKDIR /app

# RUN chmod -R 755 /app

# COPY --from=builder /app/dist dist
# COPY --from=builder /app/package.json package.json
# COPY --from=builder /app/package-lock.json package-lock.json

# RUN npm ci --frozen-lockfile

# RUN cat package.json
# RUN ls node_modules
# # ENV NODE_ENV=production

# # RUN npm cache clean --force

# CMD ["npm", "run", "start"]


FROM node:20.10.0-alpine

RUN npm cache clean --force

# Install pnpm

# Create working directory
WORKDIR /app

# Copy package files
COPY package.json ./

COPY . .

COPY ./src ./app/src

# Copy prisma files
COPY prisma ./prisma


# Install dependencies in production mode
RUN npm install

RUN npm run build


# Start the api in dev mode
CMD npm run build-prod

