services:
  mydb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      mynetwork: 
        ipv4_address: 172.28.0.4

  myapp:
    image: ghcr.io/baptiste-ferrand/dockersandbox:prod
    ports:
    - "3000:3000"
    environment:
      - HELLO="hello"
    depends_on:
      - mydb
    networks:
      mynetwork:
        ipv4_address: 172.28.0.3

networks:
  mynetwork:
    external: true